CREATE OR REPLACE DATABASE Vehicle;
GRANT USAGE ON *.* TO Vehicle@localhost IDENTIFIED BY 'cars';
GRANT ALL PRIVILEGES ON Vehicle.* TO Vehicle@localhost;
FLUSH PRIVILEGES;

USE Vehicle;

CREATE OR REPLACE TABLE suv(
    code VARCHAR(50) not null,
	model VARCHAR(50) NOT NULL,
	price float NOT NULL,
	PRIMARY KEY (code)
	);

CREATE OR REPLACE TABLE sedan(
    code VARCHAR(50) not null,
	model VARCHAR(50) NOT NULL,
	price float NOT NULL,
	PRIMARY KEY (code)
	);

CREATE OR REPLACE TABLE trucks(
    code VARCHAR(50) not null,
	model VARCHAR(50) NOT NULL,
	price float NOT NULL,
	PRIMARY KEY (code)
	);

	INSERT INTO SUV (CODE, MODEL, PRICE) VALUES ('Volkswagen-V01', 'Taos', 28000);
	INSERT INTO SUV (CODE, MODEL, PRICE) VALUES ('Nissan-N01', 'Rogue', 29200);
	INSERT INTO SUV (CODE, MODEL, PRICE) VALUES ('Chevorlet-C01', 'Equinox', 28234);
	INSERT INTO SUV (CODE, MODEL, PRICE) VALUES ('Jeep-J01', 'Compass', 35548);
	INSERT INTO SUV (CODE, MODEL, PRICE) VALUES ('Jeep-J02', 'Grand Cherokee', 40000);
	

	INSERT INTO SEDAN (CODE, MODEL, PRICE) VALUES ('Cadillac-C02', 'XTS', 45400);
	INSERT INTO SEDAN (CODE, MODEL, PRICE) VALUES ('Hyundai-H02', 'Genesis', 48400);
	INSERT INTO SEDAN (CODE, MODEL, PRICE) VALUES ('Ford-F02', 'Taurus', 30400);
	INSERT INTO SEDAN (CODE, MODEL, PRICE) VALUES ('Toyota-T02', 'Avalon', 43998);
	INSERT INTO SEDAN (CODE, MODEL, PRICE) VALUES ('Audi-A02', 'A6', 48998);


	INSERT INTO TRUCKS (CODE, MODEL, PRICE) VALUES ('Ford-F03', 'F-150', 38345);
	INSERT INTO TRUCKS (CODE, MODEL, PRICE) VALUES ('Dodge-D03', 'Ram', 36740);
	INSERT INTO TRUCKS (CODE, MODEL, PRICE) VALUES ('Chevorlet-C03', 'Silverado 1500', 36495);
	INSERT INTO TRUCKS (CODE, MODEL, PRICE) VALUES ('GMC-G03', 'Sierra 1500',37595);
	INSERT INTO TRUCKS (CODE, MODEL, PRICE) VALUES ('Nissan-N03', 'Titan', 40345);